# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AsaBrowser(object):
    def setupUi(self, AsaBrowser):
        AsaBrowser.setObjectName("AsaBrowser")
        AsaBrowser.resize(715, 712)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/EY_logon1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AsaBrowser.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(AsaBrowser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(AsaBrowser)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_path = QtWidgets.QPushButton(self.frame)
        self.pushButton_path.setObjectName("pushButton_path")
        self.verticalLayout_2.addWidget(self.pushButton_path, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(AsaBrowser)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_eng = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_eng.setObjectName("comboBox_eng")
        self.horizontalLayout_2.addWidget(self.comboBox_eng)
        self.comboBox_type = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_type.setObjectName("comboBox_type")
        self.horizontalLayout_2.addWidget(self.comboBox_type)
        self.pushButton_query = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout_2.addWidget(self.pushButton_query)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(AsaBrowser)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(AsaBrowser)
        QtCore.QMetaObject.connectSlotsByName(AsaBrowser)

    def retranslateUi(self, AsaBrowser):
        _translate = QtCore.QCoreApplication.translate
        AsaBrowser.setWindowTitle(_translate("AsaBrowser", "myBrowser"))
        self.pushButton_path.setText(_translate("AsaBrowser", "选择文件"))
        self.pushButton_query.setText(_translate("AsaBrowser", "查询"))
